apiVersion: apps/v1
kind: Deployment
metadata:
  name: me
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: me
  template:
    metadata:
      labels:
        app: me
    spec:
      containers:
        - name: me
          image: 192.168.1.48:5000/ni2faa/me:3159d98
          ports:
            - containerPort: 3000
