apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: me-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - ni2faa.ddns.net
      secretName: me-tls-cert        # cert-manager will create this
  rules:
    - host: ni2faa.ddns.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: me-svc
                port:
                  number: 80
